version: "3"

services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - API_TOKEN=${API_TOKEN}
    volumes:
      - "/bot:/bot"
      - "/storage:/storage"
    restart: always